# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASUmember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePic', models.CharField(max_length=30)),
                ('firstName', models.CharField(max_length=50)),
                ('middleName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('University', models.CharField(max_length=50)),
                ('Faculty', models.CharField(max_length=100)),
                ('collegeDepartment', models.CharField(max_length=50)),
                ('collegeID', models.CharField(max_length=8)),
                ('graduationYear', models.CharField(max_length=4)),
                ('parent1', models.CharField(max_length=50)),
                ('parent1Mobile', models.CharField(max_length=12)),
                ('parent2', models.CharField(max_length=50, null=True)),
                ('parent2Mobile', models.CharField(max_length=12, null=True)),
                ('nationalID', models.CharField(max_length=14)),
                ('passportID', models.CharField(max_length=14, null=True)),
                ('drivingID', models.CharField(max_length=14, null=True)),
                ('haveCar', models.BooleanField()),
                ('Weight', models.IntegerField()),
                ('Height', models.IntegerField()),
            ],
        ),
    ]
