# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maryamapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePic', models.ImageField(blank=True, upload_to=None)),
                ('firstName', models.CharField(max_length=20)),
                ('middleName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('Mobile', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=100)),
                ('University', models.CharField(max_length=50)),
                ('Faculty', models.CharField(max_length=100)),
                ('collegeDepartment', models.CharField(max_length=50)),
                ('collegeID', models.CharField(max_length=11)),
                ('graduationYear', models.IntegerField(choices=[(2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)], max_length=4)),
                ('parent1', models.CharField(max_length=50)),
                ('parent1Mobile', models.CharField(max_length=11)),
                ('parent2', models.CharField(blank=True, max_length=50)),
                ('parent2Mobile', models.CharField(blank=True, max_length=11)),
                ('nationalID', models.CharField(max_length=14)),
                ('passportID', models.CharField(blank=True, max_length=14)),
                ('drivingID', models.CharField(blank=True, max_length=14)),
                ('haveCar', models.BooleanField()),
                ('Weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ASUmember',
        ),
    ]
